name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Cicada
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cicada Version
        run: cicada -V

      - name: Cicada init
        run: cicada init pipeline

      - name: Cicada run
        run: cicada run .cicada/pipeline.ts
